# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b15bf39e69223d574a4c1436e65cf7b8154b4a9faf28453cf7c533c587b1d451ba0e6402b2836e2245fb5da734037853bcfb9efc64bcec70b883977b52d28deb

test:
  secret_key_base: 61522990ecd474be77f1438599dc0da4f02ef2cf8bb22635ecb045cce5ffd27e19493b77fcefa44e7a1004b0a3e3eb7d2ef2621a59905f9f4f2f77bf28afaad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
